In [1]:
# importing numpy library
import numpy as np

In [2]:
#zero elements 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
# change from float to int
np.zeros(5).astype(int)

array([0, 0, 0, 0, 0])

In [4]:
#one elements
a= np.ones(5)

In [5]:
# data type of the array
a.dtype

dtype('float64')

In [6]:
# shape of the array (rows,columns)
a.shape
np.shape(a)

(5,)

In [7]:
#reshaping an 1 dimensional array
a.reshape(5,1) 

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [8]:
# data type of elements inside the array
type(a[0])

numpy.float64

In [9]:
# What is a?
type(a)

numpy.ndarray

In [10]:
# creating empty array
v = np.empty(3)
v

array([0., 0., 0.])

In [11]:
z = np.linspace(2,10,5)
z

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
# Showing float in array to int 

z.astype(int)

array([ 2,  4,  6,  8, 10])

In [13]:
z.dtype # Hence this won't convert the dtype of an array

dtype('float64')

In [14]:
z = np.array([2,3,4,5]) # one dimensional array
z

array([2, 3, 4, 5])

In [15]:
z<4 # Boolean outcome 

array([ True,  True, False, False])

In [16]:
z[z<4] # Array , numerical outcome

array([2, 3])

In [17]:
y = np.array([[2,3,4,5,6],[7,8,4,9,8]])  # 2 dimensional array
print(y)
y.reshape(5,2)  #reshaping 2 dimensional array

[[2 3 4 5 6]
 [7 8 4 9 8]]


array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 4],
       [9, 8]])

In [18]:
myarr=np.array([[1,3,4],[5,5,3],[7,8,4]])  # 3 dimensional array
myarr

array([[1, 3, 4],
       [5, 5, 3],
       [7, 8, 4]])

In [19]:
myarr.shape

(3, 3)

In [20]:
myarr[(0,1)]  #matrix indexing

3

In [21]:
myarr[(2,1)]

8

In [22]:
# Creating array with random numbers(float)

myarr5=np.random.random((2,3))
myarr5

array([[0.20531356, 0.59898474, 0.44489106],
       [0.41688329, 0.76959472, 0.93322143]])

In [23]:
a=np.random.seed(0)  # seed is used to pick out specific sample of numnbers and it will not change even after executing the code multiple times
a=np.random.randint(10,20,size=6) #randint is used to randomly select numbers. range here is 10 to 20 and elements are 6
a 

array([15, 10, 13, 13, 17, 19])

In [24]:
#Slicing in an array  : 
a[1:3]

array([10, 13])

In [27]:
# ravel makes the ndimensional array into 1 dimensional

myarr2=np.array([[2,5,1],[3,4,1],[9,1,2]])
w=myarr2.ravel()
w

array([2, 5, 1, 3, 4, 1, 9, 1, 2])

In [28]:
#add arrays
myres= myarr+myarr2
myres

array([[ 3,  8,  5],
       [ 8,  9,  4],
       [16,  9,  6]])

In [29]:
#subtract arrays
myres=myarr-myarr2
myres

array([[-1, -2,  3],
       [ 2,  1,  2],
       [-2,  7,  2]])

In [30]:
#multiply arrays
myres=myarr.dot(myarr2)
myres

array([[47, 21, 12],
       [52, 48, 16],
       [74, 71, 23]])

In [31]:
myres.shape

(3, 3)

In [32]:
# dtype can be specified while creating an array

myarr3=np.ones((2,5),dtype=int)   
myarr3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
# if we want to add an element at the 6th posistion 

myarr4=np.ones(10,dtype=int)  
myarr4[7]=3
myarr4

#Note : The 1st position of the array is considered as 0

array([1, 1, 1, 1, 1, 1, 1, 3, 1, 1])

In [34]:
myarr4=np.zeros(10,dtype=int)
for i in range(10):
    if i%2 != 0:
        myarr4[i]=2     # We can assign the array as 2 at multiple positions
print(myarr4)

[0 2 0 2 0 2 0 2 0 2]


In [35]:
print(myarr4.ndim)#number of dimensions in an array 
print(myarr4.dtype)#the data type of elements in nd array 
print(myarr4.itemsize)#memory size occupied by each element in nd array 
print(myarr4.size)

1
int32
4
10


In [36]:
# using arange
myarr5=np.arange(101,120)
print(myarr5)

[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119]


In [37]:
#using randint
myarr5=np.random.randint(10,30,20)
myarr6=myarr5.copy()
myarr6

array([29, 28, 14, 16, 22, 11, 16, 17, 24, 27, 15, 23, 18, 19, 29, 26, 29,
       15, 25, 25])

In [38]:
#Using transpose , the rows will become columns and vice versa

ar=np.array([[2,3,4],[4,3,2],[6,5,4]])
a=ar.transpose()
a

array([[2, 4, 6],
       [3, 3, 5],
       [4, 2, 4]])

In [39]:
# slicing rows and columns together in an array

import numpy as np
myarr6=np.array([[11,22,44],[65,36,45]])
print(myarr6)

print(myarr6[0:2,2:3])

[[11 22 44]
 [65 36 45]]
[[44]
 [45]]


In [40]:
print(myarr6.min()) # minimum value in an array
print(myarr6.max()) # maximum value in an array
print(myarr6.sum()) # sum of all elements in an array
print(myarr6.prod()) # product of all the numbers in an array
print(myarr6.mean()) # mean 
print(myarr6.std()) # standard deviation
print(myarr6.var()) # variance 
print(myarr6.argmin()) # position of the minimum value
print(myarr6.argmax()) # position of the maximum value

11
65
223
1121234400
37.166666666666664
17.31489403824221
299.80555555555554
0
3


In [41]:
myarr6 * 10 #each element is multiplied by 10 . Similarly we can perform different operations for all the elements

array([[110, 220, 440],
       [650, 360, 450]])

In [42]:
# to perform operations on individial element
myarr6

array([[11, 22, 44],
       [65, 36, 45]])

In [43]:
myarr6.T  ## Transpose will make the rows as columns and cloumns as rows.

array([[11, 65],
       [22, 36],
       [44, 45]])